providers:
  openai:
    enabled: true
    api_key: ${OPENAI_API_KEY}
    base_url: https://api.openai.com/v1
    capabilities:
      - chat
      - draw
    models:
      chat:
        - name: gpt-4
          weight: 100
        - name: gpt-3.5-turbo
          weight: 80
      draw:
        - name: dall-e-3
          weight: 100
        - name: dall-e-2
          weight: 70
    
  deepseek:
    enabled: true
    api_key: ${DEEPSEEK_API_KEY}
    base_url: https://api.deepseek.com/v1
    capabilities:
      - chat
    models:
      chat:
        - name: deepseek-chat
          weight: 90
        - name: deepseek-coder
          weight: 95
    
  elevenlabs:
    enabled: true
    api_key: ${ELEVENLABS_API_KEY}
    base_url: https://api.elevenlabs.io/v1
    capabilities:
      - speak
    models:
      speak:
        - name: eleven_multilingual_v2
          weight: 100
        - name: eleven_monolingual_v1
          weight: 80

logging:
  loki:
    enabled: true
    url: ${LOKI_URL:http://localhost:3100}
    labels:
      service: april-core
      version: v2